name: dynamic_image_crop_example
description: Demonstrates how to use the dynamic_image_crop plugin.

publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dynamic_image_crop:
    path: ../

  cupertino_icons: ^1.0.2

  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
