name: dynamic_image_crop_example
description: Demonstrates how to use the dynamic_image_crop plugin.

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dynamic_image_crop:
    path: ../

  cupertino_icons: ^1.0.2

  image_picker: ^0.8.7+5
  camera: ^0.10.5+2
  path_provider:
  very_good_analysis:
  image_picker_web: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:

flutter:

  uses-material-design: true
