name: dynamic_image_crop_example
description: Demonstrates how to use the dynamic_image_crop plugin.

publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dynamic_image_crop:
    path: ../

  cupertino_icons: ^1.0.2

  image_picker: ^0.8.5+3
  image_size_getter: ^2.1.2
  camera: ^0.10.3
  path_provider:
  image_crop: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:

  uses-material-design: true

  assets:
    - images/
