name: dynamic_image_crop
description: A Flutter Package that crops the image by drawing lines or cropping into various shapes.
version: 0.0.5
repository: https://github.com/boring-km/dynamic_image_crop
issue_tracker: https://github.com/boring-km/dynamic_image_crop/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:
