name: dynamic_image_crop
description: flutter dynamic image crop package
version: 0.0.3
repository: https://github.com/boring-km/dynamic_image_crop
issue_tracker: https://github.com/boring-km/dynamic_image_crop/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:
