name: dynamic_image_crop
description: flutter dynamic image crop plugin
version: 0.0.1
homepage: https://github.com/boring-km/dynamic_image_crop

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  very_good_analysis:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.boringkm.dynamic_image_crop
        pluginClass: DynamicImageCropPlugin
      ios:
        pluginClass: DynamicImageCropPlugin
