name: check test coverage

on:
  pull_request:
    branches:
      - publish
      - example_page

jobs:
  coverage:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.10.5'
      - name: Install packages
        run: flutter pub get
      - name: run flutter test
        run: flutter test --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
