name: Example Web Deploy
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CHANGELOG.md'
    branches:
      - example_page
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: flutter --version
      - run: |
          # 1. build flutter web 
          cd example
          flutter config --enable-web
          flutter pub get
          flutter build web --release
          cd ../
      - run: |
          # 2. change path to [existed lib/main.dart path]/build/web
          cd ./example/build/web
          pwd
          git init
          git config --global user.email kms0644804@naver.com
          git config --global user.name boring-km
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/boring-km/dynamic_image_crop.git 
          git checkout -b example
          git add --all
          git commit -m "update"
          git push origin example -f